### ISSUE TITLE
JoyCon --- some buttons don't work

### ISSUE THREAD

**Issue by NanoExplorer** [Yamakaky/gyromouse#29]
Hello,
    I found this project to do exactly what I was looking for! It almost works, but when I press the ZR button on my 'right joycon' nothing happens. My configuration file is relatively simple, just for testing. Also I am on Mac M1 and I only have the right Joycon connected.
```ini
RESET_MAPPINGS
GYRO_SENS=32
S = e
W = f
N = g
E = h
R3 = c
R = GYRO_ON
ZR = k
RIGHT_STICK_MODE = NO_MOUSE
```
I expect that when I press ZR I should see it type a k, which doesn't happen. All the other options work.

Perhaps related, when I press either SL or SR I get the following crash:
```toml
name = 'gyromouse'
operating_system = 'unix:OSX'
crate_version = '0.1.0'
explanation = '''
Panic occurred in file '/Users/runner/.cargo/git/checkouts/rust-sdl2-52ead21fa771c331/27d164d/src/sdl2/controller.rs' at line 336
'''
cause = 'unhandled controller button'
method = 'Panic'
backtrace = '''

   0: 0x100a4d6a9 - gyromouse::main::ha2be660b92ece924
   1: 0x100a83dca - std::sys_common::backtrace::__rust_begin_short_backtrace::hc242b2fc2b558fd9
   2: 0x100a4b7f1 - _main'''
```
